name: EDUSİGVA - Clean Deployment
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: edusigva-465915
      
      - name: Deploy to Cloud Run
        run: |
          echo "🚀 Deploying EDUSİGVA API"
          
          gcloud run deploy edusigva-api \
            --source=. \
            --region=europe-west3 \
            --allow-unauthenticated \
            --memory=1Gi \
            --cpu=1 \
            --project=edusigva-465915
          
          echo "✅ Deployment completed!"
      
      - name: Test API
        run: |
          API_URL=$(gcloud run services describe edusigva-api --region=europe-west3 --project=edusigva-465915 --format="value(status.url)")
          echo "🔗 API URL: $API_URL"
          curl -f "$API_URL/health"
          echo ""
          echo "🎉 A - IMMEDIATE COMPLETION SUCCESS!"
